{
  "openapi": "3.0.3",
  "info": {
    "title": "File API",
    "version": "0.1.0",
    "description": "Upload and manage all files stored in epilot"
  },
  "tags": [
    {
      "name": "files",
      "description": "Files API"
    },
    {
      "name": "session",
      "description": "Session API for cookie authentication"
    }
  ],
  "security": [
    {
      "EpilotAuth": []
    },
    {
      "CookieAuth": []
    }
  ],
  "paths": {
    "/v1/files/public/upload": {
      "post": {
        "operationId": "uploadFilePublic",
        "summary": "uploadFilePublic",
        "security": [],
        "description": "Create pre-signed S3 URL to upload a file to keep temporarily (one week).\n\nUse the createFile operation to store file file permanently.\n",
        "tags": [
          "files"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UploadFilePayload"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Pre-signed URL for POST / PUT upload",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "s3ref": {
                      "allOf": [
                        {
                          "$ref": "#/components/schemas/S3Reference"
                        },
                        {
                          "example": {
                            "bucket": "epilot-files-prod",
                            "key": "123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
                          }
                        }
                      ]
                    },
                    "upload_url": {
                      "type": "string",
                      "format": "url",
                      "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf?AWSParams=123"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files/upload": {
      "post": {
        "operationId": "uploadFile",
        "summary": "uploadFile",
        "description": "Create pre-signed S3 URL to upload a file to keep temporarily (one week).\n\nUse the createFile operation to store file file permanently.\n",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "file_entity_id",
            "in": "query",
            "description": "file entity id",
            "schema": {
              "$ref": "#/components/schemas/FileEntityId"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UploadFilePayload",
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Pre-signed URL for POST / PUT upload",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "s3ref": {
                      "allOf": [
                        {
                          "$ref": "#/components/schemas/S3Reference"
                        },
                        {
                          "example": {
                            "bucket": "epilot-files-prod",
                            "key": "123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
                          }
                        }
                      ]
                    },
                    "upload_url": {
                      "type": "string",
                      "format": "url",
                      "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf?AWSParams=123"
                    },
                    "public_url": {
                      "description": "Returned only if file is permanent i.e. file_entity_id is passed",
                      "type": "string",
                      "format": "url",
                      "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files": {
      "post": {
        "operationId": "saveFile",
        "summary": "saveFile",
        "description": "Create / Update a permanent File entity\n\nMakes file object permanent\n\nSaves metadata to file entity\n",
        "tags": [
          "files"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SaveFilePayload"
              },
              "examples": {
                "S3File": {
                  "description": "Standard epilot file entity with S3 Ref",
                  "value": {
                    "file_entity_id": "string",
                    "document_type": "document",
                    "filename": "document.pdf",
                    "_tags": [
                      "string"
                    ],
                    "access_control": "private",
                    "s3ref": {
                      "bucket": "epilot-files-prod",
                      "key": "123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
                    }
                  }
                },
                "CustomFile": {
                  "description": "Custom file entity with custom download url",
                  "value": {
                    "file_entity_id": "string",
                    "document_type": "document",
                    "filename": "document.pdf",
                    "_tags": [
                      "string"
                    ],
                    "access_control": "private",
                    "custom_download_url": "https://some-api-url.com/download?file_id=123",
                    "shared_with_end_customer": true
                  }
                },
                "CustomFileWithRelations": {
                  "description": "Custom file entity with custom download url",
                  "value": {
                    "file_entity_id": "string",
                    "document_type": "document",
                    "filename": "document.pdf",
                    "_tags": [
                      "string"
                    ],
                    "access_control": "private",
                    "custom_download_url": "https://some-api-url.com/download?file_id=123",
                    "shared_with_end_customer": true,
                    "relations": [
                      {
                        "entity_id": "77a1e0cc-7b92-4d41-8cce-eefd317ec004",
                        "_schema": "contact"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created File Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FileEntity"
                }
              }
            }
          }
        }
      }
    },
    "/v1/files/{id}/download": {
      "get": {
        "operationId": "downloadFile",
        "summary": "downloadFile",
        "description": "Generate pre-signed download S3 url for a file",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/FileEntityId"
            }
          },
          {
            "name": "version",
            "in": "query",
            "description": "index of file version",
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "attachment",
            "in": "query",
            "description": "Controls the Content-Disposition header to control browser behaviour. Set to true to trigger download.",
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generated thumbnail image",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "download_url": {
                      "type": "string",
                      "format": "uri",
                      "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf?AWSParams=123"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files/download:verify": {
      "post": {
        "operationId": "verifyCustomDownloadUrl",
        "summary": "verifyCustomDownloadUrl",
        "description": "Verify a pre-signed custom download url for a file",
        "tags": [
          "files"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/VerifyCustomDownloadUrlPayload"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Download Url matches signature and has not expired",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "valid": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files:downloadFiles": {
      "post": {
        "operationId": "downloadFiles",
        "summary": "downloadFiles",
        "description": "Generate pre-signed download S3 urls for multiple files",
        "tags": [
          "files"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DownloadFilesPayload"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Generated download urls",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "download_url": {
                        "type": "string",
                        "format": "uri",
                        "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf?AWSParams=123"
                      },
                      "file_entity_id": {
                        "type": "string",
                        "format": "uuid"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files:downloadS3": {
      "post": {
        "operationId": "downloadS3File",
        "summary": "downloadS3File",
        "description": "Generate pre-signed download S3 url for a file",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "s3_key",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "s3_bucket",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "attachment",
            "in": "query",
            "description": "Controls the Content-Disposition header to control browser behaviour. Set to true to trigger download.",
            "schema": {
              "type": "boolean",
              "default": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generated thumbnail image",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "download_url": {
                      "type": "string",
                      "format": "uri",
                      "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf?AWSParams=123"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files/{id}/preview": {
      "get": {
        "operationId": "previewFile",
        "summary": "previewFile",
        "description": "Generate thumbnail preview for a file entity",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/FileEntityId"
            }
          },
          {
            "name": "version",
            "in": "query",
            "description": "index of file version",
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "w",
            "in": "query",
            "description": "width",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "h",
            "in": "query",
            "description": "height",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generated thumbnail image",
            "content": {
              "image/png": {},
              "image/jpeg": {}
            }
          }
        }
      }
    },
    "/v1/files/public/{id}/preview": {
      "get": {
        "operationId": "previewPublicFile",
        "summary": "previewPublicFile",
        "description": "Generate thumbnail preview for a public file entity",
        "security": [],
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/FileEntityId"
            }
          },
          {
            "name": "version",
            "in": "query",
            "description": "index of file version",
            "schema": {
              "type": "integer",
              "default": 0
            }
          },
          {
            "name": "w",
            "in": "query",
            "description": "width",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "h",
            "in": "query",
            "description": "height",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "org_id",
            "in": "query",
            "description": "Org id",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generated thumbnail image for a public file",
            "content": {
              "image/png": {},
              "image/jpeg": {}
            }
          }
        }
      }
    },
    "/v1/files:previewS3": {
      "get": {
        "operationId": "previewS3FileGet",
        "summary": "previewS3FileGet",
        "description": "Get thumbnail preview from an s3 reference for a file entity",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "key",
            "in": "query",
            "description": "s3 key",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "bucket",
            "in": "query",
            "description": "s3 bucket",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "w",
            "in": "query",
            "description": "width",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "h",
            "in": "query",
            "description": "height",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Generated thumbnail image",
            "content": {
              "image/png": {},
              "image/jpeg": {}
            }
          }
        }
      },
      "post": {
        "operationId": "previewS3File",
        "summary": "previewS3File",
        "description": "Generate thumbnail preview from an s3 reference for a file entity",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "w",
            "in": "query",
            "description": "width",
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "h",
            "in": "query",
            "description": "height",
            "schema": {
              "type": "integer"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/S3Reference"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Generated thumbnail image",
            "content": {
              "image/png": {},
              "image/jpeg": {}
            }
          }
        }
      }
    },
    "/v1/files/delete": {
      "delete": {
        "operationId": "deleteFile",
        "summary": "deleteFile",
        "description": "Delete file entity",
        "tags": [
          "files"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteFilePayload"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "File delete response"
          }
        }
      }
    },
    "/v1/files/session": {
      "get": {
        "operationId": "getSession",
        "summary": "getSession",
        "description": "Start a browser session by setting passed Authorization token in a server side cookie.\n\nAllows using preview urls directly in img src for private files using cookie authentication.\n",
        "tags": [
          "session"
        ],
        "responses": {
          "200": {
            "description": "Session started successfully"
          }
        }
      },
      "delete": {
        "operationId": "deleteSession",
        "summary": "deleteSession",
        "description": "End browser session by deleting token cookie",
        "tags": [
          "session"
        ],
        "responses": {
          "200": {
            "description": "Session deleted successfully"
          }
        }
      }
    },
    "/v1/files/{id}/public/links": {
      "post": {
        "operationId": "generatePublicLink",
        "summary": "generatePublicLink",
        "description": "Generates a public link to access the private files\n",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/FileEntityId"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Returns the public link which can be used to access the file later",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "example": "https://file.sls.epilot.io/v1/files/public/links/3ef5c6d9-818d-45e6-8efb-b1de59079a1c/invoice-2023-12.pdf"
                }
              }
            }
          }
        }
      },
      "get": {
        "operationId": "getAllPublicLinksForFile",
        "summary": "getAllPublicLinksForFile",
        "description": "Not yet implemented; This API would fetches all the public links that are previously generated for a file",
        "x-not-implemented": true,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "ID of the file entity",
              "example": "13d22918-36bd-4227-9ad4-2cb978788c8d"
            }
          }
        ],
        "tags": [
          "files"
        ],
        "responses": {
          "200": {
            "description": "Public links of a file retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/PublicLink"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/files/public/links/{id}/{filename}": {
      "get": {
        "operationId": "accessPublicLink",
        "summary": "accessPublicLink",
        "security": [],
        "description": "Redirects to a accessible signed url for the respective file associated to the public link",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "Id of the publicly generated link",
              "example": "13d22918-36bd-4227-9ad4-2cb978788c8d"
            }
          },
          {
            "name": "filename",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "Name of the file",
              "example": "invoice-2023-12.pdf"
            }
          }
        ],
        "tags": [
          "files"
        ],
        "responses": {
          "302": {
            "description": "Redirect to signed URL where the caller can access the file"
          }
        }
      }
    },
    "/v1/files/public/links/{id}": {
      "delete": {
        "operationId": "revokePublicLink",
        "summary": "revokePublicLink",
        "security": [],
        "description": "Not yet implemented; This operation would revokes a given public link by ID",
        "x-not-implemented": true,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "description": "Id of the publicly generated link",
              "example": "13d22918-36bd-4227-9ad4-2cb978788c8d"
            }
          }
        ],
        "tags": [
          "files"
        ],
        "responses": {
          "204": {
            "description": "Revokes a public link successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "example": "https://file.sls.epilot.io/v1/files/public/links/3ef5c6d9-818d-45e6-8efb-b1de59079a1c"
                }
              }
            }
          }
        }
      }
    },
    "/v2/files/upload": {
      "post": {
        "operationId": "uploadFileV2",
        "summary": "uploadFileV2",
        "description": "Create pre-signed S3 URL to upload a file to keep temporarily (one week). - v2\n\nUse the createFile operation to store file file permanently.\n",
        "tags": [
          "files"
        ],
        "parameters": [
          {
            "name": "file_entity_id",
            "in": "query",
            "description": "file entity id",
            "schema": {
              "$ref": "#/components/schemas/FileEntityId"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UploadFilePayload",
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Pre-signed URL for POST / PUT upload",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FileUpload"
                }
              }
            }
          }
        }
      }
    },
    "/v2/files": {
      "post": {
        "operationId": "saveFileV2",
        "summary": "saveFileV2",
        "description": "Create / Update a permanent File entity\n\nMakes file object permanent\n\nSaves metadata to file entity\n",
        "tags": [
          "files"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SaveFilePayloadV2"
              },
              "examples": {
                "S3File": {
                  "description": "Standard epilot file entity with S3 Ref",
                  "value": {
                    "file_entity_id": "string",
                    "document_type": "document",
                    "filename": "document.pdf",
                    "_tags": [
                      "string"
                    ],
                    "access_control": "private",
                    "s3ref": {
                      "bucket": "epilot-files-prod",
                      "key": "123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
                    }
                  }
                },
                "CustomFile": {
                  "description": "Custom file entity with custom download url",
                  "value": {
                    "file_entity_id": "string",
                    "document_type": "document",
                    "filename": "document.pdf",
                    "_tags": [
                      "string"
                    ],
                    "access_control": "private",
                    "custom_download_url": "https://some-api-url.com/download?file_id=123",
                    "shared_with_end_customer": true
                  }
                },
                "CustomFileWithRelations": {
                  "description": "Custom file entity with custom download url",
                  "value": {
                    "file_entity_id": "string",
                    "document_type": "document",
                    "filename": "document.pdf",
                    "_tags": [
                      "string"
                    ],
                    "access_control": "private",
                    "custom_download_url": "https://some-api-url.com/download?file_id=123",
                    "shared_with_end_customer": true,
                    "relations": [
                      {
                        "entity_id": "77a1e0cc-7b92-4d41-8cce-eefd317ec004",
                        "_schema": "contact"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created File Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FileEntity"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "EpilotAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "Authorization header with epilot OAuth2 bearer token",
        "bearerFormat": "JWT"
      },
      "CookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "token",
        "description": "Cookie with epilot OAuth2 token"
      }
    },
    "schemas": {
      "EntityId": {
        "type": "string",
        "example": "ef7d985c-2385-44f4-9c71-ae06a52264f8"
      },
      "EntitySlug": {
        "description": "URL-friendly identifier for the entity schema",
        "type": "string",
        "example": "contact"
      },
      "FileEntityId": {
        "type": "string",
        "example": "ef7d985c-2385-44f4-9c71-ae06a52264f8"
      },
      "FileEntity": {
        "type": "object",
        "properties": {
          "_id": {
            "$ref": "#/components/schemas/FileEntityId"
          },
          "filename": {
            "type": "string",
            "example": "document.pdf"
          },
          "access_control": {
            "type": "string",
            "default": "private",
            "enum": [
              "private",
              "public-read"
            ]
          },
          "public_url": {
            "description": "Direct URL for file (public only if file access control is public-read)",
            "type": "string",
            "format": "url",
            "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
          },
          "type": {
            "description": "Human readable type for file",
            "type": "string",
            "enum": [
              "document",
              "document_template",
              "text",
              "image",
              "video",
              "audio",
              "spreadsheet",
              "presentation",
              "font",
              "archive",
              "application",
              "unknown"
            ]
          },
          "mime_type": {
            "type": "string",
            "description": "MIME type of the file",
            "example": "application/pdf"
          },
          "size_bytes": {
            "type": "integer",
            "minimum": 0,
            "description": "File size in bytes"
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "s3ref": {
                  "$ref": "#/components/schemas/S3Reference"
                }
              }
            }
          }
        }
      },
      "UploadFilePayload": {
        "type": "object",
        "properties": {
          "filename": {
            "type": "string",
            "example": "document.pdf"
          },
          "mime_type": {
            "description": "MIME type of file",
            "type": "string",
            "example": "application/pdf",
            "default": "application/octet-stream"
          },
          "metadata": {
            "type": "object",
            "additionalProperties": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "example": {
              "color": "blue"
            },
            "description": "Allows passing in custom metadata for the file, expects key-value pairs of string type"
          }
        },
        "required": [
          "filename"
        ]
      },
      "FileUpload": {
        "type": "object",
        "properties": {
          "s3ref": {
            "allOf": [
              {
                "$ref": "#/components/schemas/S3Reference"
              },
              {
                "example": {
                  "bucket": "epilot-files-prod",
                  "key": "123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
                }
              }
            ]
          },
          "upload_url": {
            "type": "string",
            "format": "url",
            "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/temp/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf?AWSParams=123"
          },
          "public_url": {
            "description": "Returned only if file is permanent i.e. file_entity_id is passed",
            "type": "string",
            "format": "url",
            "example": "https://epilot-files-prod.s3.eu-central-1.amazonaws.com/123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
          }
        }
      },
      "DownloadFilesPayload": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "$ref": "#/components/schemas/FileEntityId"
            },
            "version": {
              "type": "integer",
              "description": "File version",
              "example": 0
            }
          },
          "required": [
            "id"
          ]
        }
      },
      "CommonSaveFilePayload": {
        "type": "object",
        "properties": {
          "file_entity_id": {
            "type": "string",
            "description": "if passed, adds a new version to existing file entity"
          },
          "document_type": {
            "type": "string",
            "enum": [
              "document",
              "document_template",
              "text",
              "image",
              "video",
              "audio",
              "spreadsheet",
              "presentation",
              "font",
              "archive",
              "application",
              "unknown"
            ]
          },
          "filename": {
            "type": "string",
            "example": "document.pdf"
          },
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "access_control": {
            "type": "string",
            "default": "private",
            "enum": [
              "private",
              "public-read"
            ]
          },
          "relations": {
            "type": "array",
            "description": "List of entities to relate the file to",
            "items": {
              "$ref": "#/components/schemas/FileRelationItem"
            }
          }
        },
        "additionalProperties": true
      },
      "SaveS3FilePayload": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CommonSaveFilePayload"
          },
          {
            "type": "object",
            "properties": {
              "s3ref": {
                "$ref": "#/components/schemas/S3Reference"
              }
            },
            "required": [
              "s3ref"
            ]
          }
        ]
      },
      "SaveCustomFilePayload": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CommonSaveFilePayload"
          },
          {
            "type": "object",
            "properties": {
              "custom_download_url": {
                "description": "Custom external download url used for the file",
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "custom_download_url"
            ]
          }
        ]
      },
      "SaveFilePayload": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/SaveS3FilePayload"
          },
          {
            "$ref": "#/components/schemas/SaveCustomFilePayload"
          }
        ]
      },
      "SaveFilePayloadV2": {
        "type": "object",
        "properties": {
          "s3ref": {
            "type": "object",
            "properties": {
              "bucket": {
                "type": "string",
                "example": "epilot-files-prod"
              },
              "key": {
                "type": "string",
                "example": "123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
              }
            },
            "required": [
              "bucket",
              "key"
            ]
          },
          "filename": {
            "type": "string",
            "example": "document.pdf"
          },
          "file_entity_id": {
            "type": "string",
            "description": "if passed, adds a new version to existing file entity"
          },
          "document_type": {
            "type": "string",
            "enum": [
              "document",
              "document_template",
              "text",
              "image",
              "video",
              "audio",
              "spreadsheet",
              "presentation",
              "font",
              "archive",
              "application",
              "unknown"
            ]
          },
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "access_control": {
            "type": "string",
            "default": "private",
            "enum": [
              "private",
              "public-read"
            ]
          },
          "custom_download_url": {
            "description": "Custom external download url used for the file",
            "type": "string",
            "format": "uri"
          }
        },
        "additionalProperties": true,
        "required": [
          "s3ref",
          "filename"
        ]
      },
      "DeleteFilePayload": {
        "type": "object",
        "properties": {
          "s3ref": {
            "$ref": "#/components/schemas/S3Reference"
          }
        },
        "required": [
          "s3ref"
        ]
      },
      "VerifyCustomDownloadUrlPayload": {
        "type": "object",
        "properties": {
          "custom_download_url": {
            "description": "Custom external download url with signature and expiration time",
            "type": "string",
            "format": "uri",
            "example": "https://some-api-url.com?file_id=123&expires_at=1699273500029&signature=abcdefg"
          }
        },
        "required": [
          "custom_download_url"
        ]
      },
      "S3Reference": {
        "type": "object",
        "properties": {
          "bucket": {
            "type": "string",
            "example": "epilot-files-prod"
          },
          "key": {
            "type": "string",
            "example": "123/4d689aeb-1497-4410-a9fe-b36ca9ac4389/document.pdf"
          }
        },
        "required": [
          "bucket",
          "key"
        ]
      },
      "FileRelationItem": {
        "type": "object",
        "properties": {
          "entity_id": {
            "$ref": "#/components/schemas/EntityId"
          },
          "_schema": {
            "$ref": "#/components/schemas/EntitySlug"
          },
          "_tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "entity_id"
        ]
      },
      "PublicLink": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID of the public link",
            "example": "3ef5c6d9-818d-45e6-8efb-b1de59079a1c"
          },
          "link": {
            "type": "string",
            "description": "Public link of the file",
            "example": "https://file.sls.epilot.io/v1/files/public/links/3ef5c6d9-818d-45e6-8efb-b1de59079a1c"
          },
          "last_accessed_at": {
            "type": "string",
            "description": "The most recent timestamp when the file was accessed"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://file.sls.epilot.io"
    },
    {
      "url": "https://file.sls.epilot.io"
    }
  ]
}
